name: Angular CI
description: 'Builds, tests, and deploys a Node.js Angular application'

inputs:
  node_version:
    description: 'Node Version'
  docker_image_name:
    description: 'Docker image name'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  sonar_token:
    description: 'Token for SonarCloud access'
    required: true
  dockerhub_username:
    description: 'DockerHub username'
    required: true
  dockerhub_token:
    description: 'DockerHub token for authentication'
    required: true
  gitleaks_token:
    description: 'Organisational token for Gitleaks'
    required: false # only required for Organizations, not personal accounts

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate conventional commits
      uses: wagoid/commitlint-github-action@v6    

    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # auto assigned by GitHub when actions gets kicked off. No need to define
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_token != '' && inputs.gitleaks_token || 'unset' }} 